# Generated by Django 4.1.7 on 2023-03-11 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='BookTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='BookPartTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('bookTemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='app.booktemplate')),
            ],
        ),
        migrations.CreateModel(
            name='BookPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.book')),
                ('bookPart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bookparttemplate')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='bookTemplate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.booktemplate'),
        ),
    ]
