# Generated by Django 4.1.7 on 2023-03-11 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookpart',
            old_name='bookPart',
            new_name='bookPartTemplate',
        ),
        migrations.AlterField(
            model_name='bookpart',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='app.book'),
        ),
    ]
